# Remove only this tool's registration and owned stubs. Leave the shared submenu.
param([string]$ToolsDir = "C:\dev\tools")
$ErrorActionPreference = "Stop"
if ($env:OS -ne "Windows_NT") { throw "uninstall.ps1 requires Windows. On macOS use uninstall.sh." }
$stub = Join-Path $ToolsDir "img-to-svg.bat"
$expectedStub = "call `"$PSScriptRoot\img-to-svg.bat`" %*"
if (-not (Test-Path $stub) -or -not ((Get-Content $stub) -contains $expectedStub)) {
    Write-Host "No stub owned by this clone. Leaving the current installation alone."
    return
}
$expectedCommand = "cmd.exe /k `"`"$ToolsDir\img-to-svg.bat`" `"%1`"`""
foreach ($ext in @('.jpg', '.jpeg', '.png', '.webp', '.bmp', '.tiff', '.tif')) {
    $verb = "HKCU:\Software\Classes\SystemFileAssociations\$ext\shell\MikesTools\shell\ImgToSvg"
    $commandKey = Join-Path $verb "command"
    if ((Test-Path $commandKey) -and (Get-Item $commandKey).GetValue('') -eq $expectedCommand) {
        Remove-Item $verb -Recurse -Force
    }
}
Remove-Item $stub -Force
$bashStub = Join-Path $ToolsDir "img-to-svg"
# Only delete the exact Bash forwarder generated by Write-BatStub.
if (Test-Path $bashStub) {
    $content = (Get-Content $bashStub -Raw).Replace("`r`n", "`n").TrimEnd()
    $expectedBash = @'
#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "$SCRIPT_DIR/img-to-svg.bat" "$@"
'@
    if ($content -eq $expectedBash.Replace("`r`n", "`n").TrimEnd()) { Remove-Item $bashStub -Force }
}
Remove-Item (Join-Path $env:LOCALAPPDATA "img-to-svg\icons\img-to-svg.ico") -Force -ErrorAction SilentlyContinue
Write-Host "Uninstalled img-to-svg. Shared PATH entries, Python packages and StarVector checkout were kept."
